version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: jinja2
    versions:
    - 2.11.3
  - dependency-name: pip-tools
    versions:
    - 6.0.0
    - 6.0.1
